name: Docker Build & Run

on:
  schedule:
    - cron: '0 11,23 * * *'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    environment: prod

    steps:
    - uses: actions/checkout@v4
    - name: Create env file
      run: |
        touch .env
        echo BOOKING_ID=${{ secrets.BOOKING_ID }} >> .env
        echo SHIP_CODE=${{ secrets.SHIP_CODE }} >> .env
        echo SAIL_DATE=${{ secrets.SAIL_DATE }} >> .env
        echo MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} >> .env
        echo MAIL_SENDER=${{ secrets.MAIL_SENDER }} >> .env
        echo MAIL_RECIPIENTS=${{ secrets.MAIL_RECIPIENTS }} >> .env
    - name: Create volume
      run: docker volume create app_data
    - name: Build the Docker image
      run: docker build -t jkaisix/rc-webscraper .
    - name: Run container
      run: docker run --env-file .env -v app_data:/app jkaisix/rc-webscraper
    - name: Run container (interactive)
      run: docker run -d -it -v app_data:/app jkaisix/rc-webscraper sh
    - name: Get data from Docker container
      run: |
        docker cp $(docker ps --latest -q):/app/rc_log.txt .
        docker cp $(docker ps --latest -q):/app/rc_prices.csv .
    - name: commit
      run: |
        git config user.name "github-actions"
        git config user.email "<>"
        git add rc_log.txt rc_prices.csv
        git commit -m "Updating rc files..."
        git push
